name: Docker Build - DEV
on:
  push:
    branches:
      - 'feature/*'
jobs:
  Docker-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Docker tag
        run: |
          git fetch --no-tags --depth=1
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "IMAGE_DATE_TAG=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.REGISTRY_USERNAME }}/${{ github.event.repository.name }}:develop-${{ env.IMAGE_DATE_TAG }}-${{ env.SHORT_SHA }}
